extern const unsigned char FD_BUSY[];
extern const unsigned char FD_IDLE[];
extern const unsigned char TAPE_IDLE[];
extern const unsigned char TAPE_LOADING[];
extern const unsigned char TAPE_SAVING[];
extern const int MENU_wid;
extern const int MENU_hei;
extern const unsigned char MENU[];
extern const int PAUSE_wid;
extern const int PAUSE_hei;
extern const unsigned char PAUSE[];
extern const int CAPS_wid;
extern const int CAPS_hei;
extern const unsigned char CAPS[];
extern const int KANA_wid;
extern const int KANA_hei;
extern const unsigned char KANA[];
extern const int INS_wid;
extern const int INS_hei;
extern const unsigned char INS[];
