name: Build Test on Pull-Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkout_Tsugaru
      run: git clone https://github.com/captainys/TOWNSEMU.git
    - name: mkdir
      run: mkdir ci
    - name: cmake
      run: cmake ../src
      working-directory: ./ci
    - name: build
      run: cmake --build . --config Release
      working-directory: ./ci
    - name: make_zip
      run: |
          cmake -E copy ./main_cui/Release/Mutsu_CUI.exe .
          cmake -E copy ../readme.md .
          cmake -E copy ../command.md .
          cmake -E tar cvf windows_binary_latest.zip --format=zip Mutsu_CUI.exe readme.md command.md
      working-directory: ./ci



  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkout_Tsugaru
      run: git clone https://github.com/captainys/TOWNSEMU.git
    - name: mkdir
      run: mkdir ci_ubuntu
    - name: install-OpenGL
      run: sudo apt-get install libglu1-mesa-dev mesa-common-dev
    - name: cmake
      run: cmake ../src -DCMAKE_BUILD_TYPE=Release
      working-directory: ./ci_ubuntu
    - name: build
      run: cmake --build .
      working-directory: ./ci_ubuntu



  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkout_Tsugaru
      run: git clone https://github.com/captainys/TOWNSEMU.git
    - name: mkdir
      run: mkdir ci_macos
    - name: cmake
      run: cmake ../src -DCMAKE_BUILD_TYPE=Release
      working-directory: ./ci_macos
    - name: build
      run: cmake --build .
      working-directory: ./ci_macos
